### ISSUE TITLE
配布用バナー4種

### ISSUE THREAD

**Issue by featherplain** [featherplain/wct2015#22]
- 依頼者: @featherplain
- 期日: 8/10
- 目的: 配布用のバナーを作成して Camp サイトに掲載します。
## サイズ

スプレッドシートの [画像] シートに作成するバナーのリストがあります。
- `300*300`: サイドバー掲載用
- `250*250`
- `234*60`: ja.wordpress.org および https://japan.wordcamp.org/ にも掲載
- `468*60`
## 参考
- 2013: [https://tokyo.wordcamp.org/2013/banner01/](https://tokyo.wordcamp.org/2013/banner01/)
- 2014: [https://tokyo.wordcamp.org/2014/about/banners/](https://tokyo.wordcamp.org/2014/about/banners/)
## 素材

Google Drive に一通り素材を `src/` フォルダの中に入れているので好きに使ってください!

**Comment by funteractive** [comment]
@featherplain 4種類作りました。ドライブに入れてあります。よろしく！
https://drive.google.com/open?id=0B1F5H-rS6_vvflJXUXA0THZraElqa1NKOWJvamVoOHJhRW0yRVdUdUR4NXZfV0pUVkJSVVk
