### ISSUE TITLE
Central 用バナー

### ISSUE THREAD

**Issue by featherplain** [featherplain/wct2015#23]
- 依頼者: @featherplain
- 期日: 8/13
- 目的: [WordCamp Central](https://central.wordcamp.org/) に掲載するバナーを作成します。
## 基本要素
- WordCamp Tokyo 2015

わぷーはあってもなくても OK
## デザインについて

公式ドキュメントより

> いい例:
> 
> WordCamp の地域に紐ついた写真
> シンプルで、明るいカラーのイラスト
> 
> 悪い例:
> 
> テキストやロゴ、シンボルなどを含むバナー
> 複雑なイラスト

とありますが、素材はそろっているので、ロゴと背景にするといいと思います。
印刷班作成の背景を使っても OK ですし、何か和柄の背景を当て込んでも OK です。

和柄素材: [http://japanese-pattern.info/](http://japanese-pattern.info/)
## サイズ

`926*160`
### 注意事項

提出できるサイズは1サイズだけですが、トリミングして使いまわされるので、小さいサイズでもテキストがなるべく途切れないようにするとよりいいと思います!

トリミングして使われるサイズの例は以下の2つ
- W82 x H37: [http://central.wordcamp.org/schedule/](http://central.wordcamp.org/schedule/)
- W130 x H60: [http://central.wordcamp.org/schedule/past-wordcamps/](http://central.wordcamp.org/schedule/)
## 参考
- 掲載先: [http://central.wordcamp.org/wordcamps/wordcamp-tokyo-3/](http://central.wordcamp.org/wordcamps/wordcamp-tokyo-3/)
- 掲載例: [http://central.wordcamp.org/wordcamps/wordcamp-kansai/](http://central.wordcamp.org/wordcamps/wordcamp-kansai/)
- 作成ルール: [http://plan.wordcamp.org/first-steps/web-presence/your-page-on-central-wordcamp-org/](http://plan.wordcamp.org/first-steps/web-presence/your-page-on-central-wordcamp-org/)
## 素材

Google Drive に一通り素材を `src/` フォルダの中に入れているので好きに使ってください!

**Comment by funteractive** [comment]
@featherplain セントラル用作りました。格ゲー感押していきます！
https://drive.google.com/open?id=0B1F5H-rS6_vvfkpSekUwaEZrSEdkbjNCbmd4Sjh1SldvakNPNTJhNnNHRkxBM1lvRGJleUk
