### ISSUE TITLE
ページ作成_バナー配布

### ISSUE THREAD

**Issue by featherplain** [featherplain/wct2015#28]
@luckyusapyon :
- 依頼者: @featherplain
- 期限: 8/12
- 目的: 配布バナーページを作成して、サイトの認知・拡散に使用します。

昨年度のページを参考にバナー配布のページ作成をお願いします。
Camp サイトで直接作業してもらって、完了したら [下書きで保存] してお知らせください!
https://tokyo.wordcamp.org/2014/about/banners/
- 固定ページで作成
- ページタイトル: 「配布バナー」
- 掲載バナー: 250x250, 468x60, 234x60 の三種類(300x300 はサイドバー掲載用なので必要なし)
- スラッグ: banners

バナーは Google Drive の `banner/01_配布用` にあります。

**Comment by ghost** [comment]
一応 完了して下書き保存しておきました．
また,去年と同様 バナー画像はGoogle Drive から wordpress.org側に保存して，そこからリンク画像にしました．

**Comment by featherplain** [comment]
@luckyusapyon 
ありがとうございます!ばっちりです!
明日の午前中公開しますね。
