### ISSUE TITLE
スマホでページロードするときに余白が見える

### ISSUE THREAD

**Issue by featherplain** [featherplain/wct2015#52]

**Comment by featherplain** [comment]
viewport の指定がうまくいっていないのかも
- https://developers.google.com/speed/docs/insights/ConfigureViewport?hl=ja
- http://www.w3.org/TR/css-device-adapt/#the-viewport-rule

**Comment by k4zuki02h4t4** [comment]
突然失礼しまーす。
くっくると申します(・∀・)

原因は、Twitter ウィジェットです。

```
.twitter-timeline {
    position: relative !important;
}
```

これで解決はできると思います。たぶん !
Chrome Developer tools のレスポンシブ確認用のあれ（すみません、名前が分からなくて）で再現していたのですが、上記 CSS 追加で再現しなくなりました。

```
<meta name="viewport" content="width=device-width, initial-scale=1">
```

でも大丈夫です。

**Comment by featherplain** [comment]
@kuck1u さん

Twitter でしたかー。
実はサイトに設置してる Facebook Like Box が表示されず、動作が不安定ということもあって Jetpack の SNS ウィジェットの設置自体をやめることにしました。仕様も変わるかもしれませんしね。。。

代わりにウィジェットに影響されないボタン設置で対応しました!
https://tokyo.wordcamp.org/2015/
これでページロードの問題も解消するかと思いますー。

ご報告ありがとうございましたm(_ _)m
